### ISSUE TITLE
¿Qué tipo de virtualización usarías en diferentes casos reales que te puedas encontrar?

### ISSUE THREAD

**Issue by JJ** [JJ/IV16-17#1]
A lo largo de la asignatura se virtualizará una aplicación concreta, pero en otros casos, otras asignaturas o incluso un trabajo que se esté haciendo fuera de la ETSIIT, se usarán diferentes tipos de virtualización. ¿En qué caso o casos se puede aplicar cada técnica de virtualización?

**Comment by elsudano** [comment]
A la hora de montar un CPD tienes que conocer las diferentes maneras de virtualizar ya que para según que casos deberas usar una u otra, me refiero a que se puede virtualizar hardware completo (por ejemplo con VmWare), se puede virtualizar solamente un software (por ejemplo un emulador)

**Comment by JJ** [comment]
Por favor, no volváis a poner "close" nada en los commits a este repositorio. Ya habéis cerrado este issue 3 o 4 veces. Los close y las referencias a issues tenéis que ponerlas en *vuestros* repositorios.

**Comment by MarFerPra** [comment]
* **Virtualización para entornos de desarrollo**: Programar utilizando distintas versiones de Ruby con [RVM](https://rvm.io/rvm/basics).
*  **Virtualización de aplicaciones**: Para tener un entorno aislado de los demás por temas de seguridad. (i.e Distribución Linux [Qubes](https://www.qubes-os.org/) o [Windows Edge Virtual instances](http://arstechnica.com/information-technology/2016/09/windows-10-will-soon-run-edge-in-a-virtual-machine-to-keep-you-safe/))
* **Virtualización plena**: Uso de un sistema operativo para un determinado fin sin alterar la máquina huésped. [Kali Linux](http://es.docs.kali.org/general-use-es/kali-linux-en-virtual-box)
*  **Virtualización a nivel de sistema operativo:** Para el despliege de distintos servicios web sobre una misma máquina, compartiendo características de una misma instancia del kernel de Linux entre varios SO. ([Docker](https://es.wikipedia.org/wiki/Docker_(software))

**Comment by sergiocaceres** [comment]
- La virtualización plena cuando necesite trabajar con máquinas virtuales en VirtualBox o VMware por ejemplo, ya que en algunos casos la virtualización de aplicaciones no funciona de manera correcta.
- La virtualización de aplicaciones cuando necesite ejecutar alguna aplicación de Windows en Linux, por ejemplo, usando WINE.

**Comment by kaizensamuel** [comment]
Virtualizacion de recursos
Para redes virtuales privadas, almacenamiento con gestores de volumenes,etc.....

Virtualización de plataforma:

• Emulacion o simulación.Ejecutar programas en una plataforma distinta a la que tenemos,                                                       para emular el hardware de maquinas recreativas.
• Virtualización nativa o completa.Permitir a un sistema operativo invitado, correr de
forma aislada sobre el mismo tipo de CPU que la maquina anfitriona.
• Virtualización asistida por hardware.
• Paravirtualizacion.
• Virtualización a nivel de sistema operativo.Cuando necesitamos que corran varios SO en una misma maquina  de forma independiente.

Virtualización de aplicaciones cuando necesitamos ejecutar alguna aplicación de otro sistema,por ejemplo wine para ejecutar aplicaciones de windows en linux.

**Comment by josejapch** [comment]
**- Virtualización plena:** En mi caso estuve trabajando con este tipo de virtualización para poder tener en mi ordenador tanto Windows como Linux.
**- Virtualización de aplicación:** Para poder ejecutar una aplicación en distintos sistemas operativos o ejecutar distintas versiones de un mismo programa en paralelo.
**- Virtualización de entornos de desarrollo:** Para cuando se necesita trabajar con un lenguaje en una versión concreta sin tener que modificar la versión que tienes en el sistema.

**Comment by Sergiopopoulos** [comment]
**- Virtualización plena:** Cuando lo que queremos es una simulación completa de un SO, en el que podemos tener un SO independiente del nativo.

**- virtualización parcial:**  Si queremos virtualizar parte del SO, en el que algunas instancias del mismo son compartidas y otras son virtualizadas.

**- virtualización de sistema operativo:** Cuando lo que queremos es ejecutar múltiples servidores virtuales en un mismo entorno físico, y nos puede beneficiar para que las actividades en un entorno virtual no afecten a los demás dentro del mismo entorno físico.

**- virtualización de aplicaciones:**  En el caso de que necesitemos ejecutar una aplicación para un SO distinto al que está en ejecución, como cuando queremos ejecutar aplicaciones de Windows en Linux.

**- virtualización de entornos de desarrollo:** Nos permite crear varios entornos, útil cuando necesitemos ejecutar un código y saber si es compatible en las diferentes versiones de dicho lenguaje.

**Comment by manuelalonsobraojos** [comment]
- **Virtualización plena** : cuando necesitamos trabajar con distintos sistemas operativos, utilizaríamos por ejemplo, VirtualBox y VmWare.  
- **Virtualización de aplicaciones**: lo utilizaríamos en el caso de que queramos ejecutar aplicaciones solo válidas para un sistema operativo en otro, como por ejemplo el programa Wine, que carga programas de Windows en Linux.

- **Virtualización en entornos de desarrollo**: es útil cuando estamos necesitemos trabajar con una determinada versión de un lenguaje sin modificar la versión que ya tengamos en nuestro sistema

**Comment by fjfernandez93** [comment]
- **Virtualización plena:** si necesito trabajar con un sistema operativo concreto pero no quiero instalarlo directamente en un PC, por ejemplo utilizando VirtualBox o VMWare.
- **Virtualización parcial:** puede ser util si se quiere crear un sistema en los que se quiere utilizar un mismo recurso para muchos usuarios pero que lo perciban como si su "división" fuera un recurso completo. Por ejemplo, al montar un VPS se virtualizan recursos como la RAM o la CPU.
-  **Virtualización a nivel de sistema operativo:** también en el caso de un VPS, para aislar los distintos servidores virtuales de los clientes.
- **Virtualización de aplicaciones:** cuando por ejemplo tengamos que desplegar una infraestructura en un sistema operativo concreto sí o sí, pero necesitemos de un servicio o aplicación que no esté disponible para ese SO.
- **Virtualización de entornos de desarrollo:** util por ejemplo para evitar conflictos entre las versiones de paquetes, módulos, librerías, etc. que usamos en los diferentes proyectos que llevamos a cabo en una misma máquina.

**Comment by maribhez** [comment]
* _Virtualización plena:_ Aunque existen muchas otras formas, ésta podría ser una oportunidad de tener disponible una copia de seguridad de un sistema configurado por nosotros por temas de seguridad; para tener a mano una solución en caso de catástrofe (del tipo que sea). Por supuesto, también podría de gran utilidad tener un sistema completo para trabajar con él y conseguir nuestro trabajo. 

* _Virtualización parcial:_ Dado que un dispositivo puede hacer creer a los usuarios de nuestro sistema que están accediendo a un mismo recurso completo cuando en realidad está configurado de manera completamente diferente podríamos usar hardware antiguo para su configuración. 

* _Virtualización a nivel de SO:_  Un buen caso para virtualización a este nivel sería querer solucionar las incompatibilidades que surgen a la hora de transferir información entre diferentes sistemas operativos, quedando eliminada al virtualizar el mismo. 

* _Virtualización de aplicaciones:_ En este tipo se nos pueden plantear, entre otras cosas, las aplicaciones que llevan a cabo actualizaciones asiduas. Con una virtualización de dicha aplicación es posible comprobar si la actualización en nuestro sistema va a traer problemas o, por supuesto, permitirá mantener ambas versiones en la misma máquina sin que intercedan entre ellas.
 
* _Virtualización de entornos de desarrollo:_ Cuando varias personas trabajan en el mismo proyecto y a una de ellas les llega de nuevas puede ser necesario virutaliar el entorno de desarrollo a usar por no disponer del conveniente, poniéndose a la par de sus compañeros y trabajando con la misma configuración desde ese momento.

**Comment by LuisGi93** [comment]
* **Virtualización plena**: cuando quiera ejecutar diferentes sistemas operativos aislados entre si sobre mi ordenador sin tener que preocuparme de si un fallo de seguridad o mala configuración en uno de ellos afecte al resto del sistema. Un ejemplo [QubesOS](https://www.qubes-os.org/).

* **Virtualización parcial**: para que mi ordenador vea el almacenamiento  de mi equipo como un "todo". Ejemplo  RAID1.

* **Paravirtualización**: para realizar cualquier operación por parte del SO cliente tal que sea sumamente costosa realizarla en un ambiente virtualizado y por tanto sea mejor pasarle esta tarea al SO huesped. 

* **Virtualización a nivel de sistema operativo** para aislar aplicaciones que pueden ser vulnerables.

* **Virtualización de aplicaciones** cuando necesito utilizar una aplicación de un sistema operativo en otro diferente el cual no dispone de la aplicación.

* **Virtualización de entornos de desarrollo** para poder "testear" mi aplicación en diferentes entornos.

**Comment by jfranguerrero** [comment]
- Virtualización plena: Cuando deseo un sistema completo con total independecia del SO nativo proporcionando un extra de seguridad y fiabilidad al SO anfitrión.

- Virtualización parcial: Para compartir recursos o si se quieren usar determinados recursos de otro tipo de sistema operativo.

- Virtualización a nivel de sistema operativo: Para ofrecer servicios a diversos clientes sin interferir entre ellos ni tener carencias de seguridad. Estamos en el caso de los famosos VPS.

- Virtualización de aplicaciones: Uso de aplicaciones que tengan un correcto funcionamiento en otro SO que no tenemos como anfitrión.

- Virtualización de entornos de desarrollo: Para comprobar los distintos errores de productos desarrollados sin dañar el sistema anfitrión.

**Comment by Antkk10** [comment]
- **Virtualización plena**: la utilizo para para poder usar tanto Windows como Ubuntu al mismo tiempo. Por ejemplo necesito trabajar con Windows y al mismo tiempo estoy trabajando en Ubuntu, no quiero reiniciar el ordenador y acceder a Windows instalado en mi ordenador de forma nativa a través del grub. Pues instalo una máquina virtual (VirtualBox) y en ella instalo Windows, así puedo trabajar con los dos SO a la vez.

- **Virtualización parcial**: Es utilizado para compartir recurso/s con varios usuarios. Estos usuarios creen usar un recurso completo.

- **Virtualización a nivel de sistema operativo**: también conocido como Virtualización basado en contenedores, es una opción ideal para los proveedores de alojamiento que necesitan una manera eficiente y segura para ofrecer sistemas operativos para que los clientes ejecuten sus servicios en ellos.

- **Virtualización de aplicaciones**: Crea un entorno abstracto, haciendolo independiente del entorno físico. Por ejemplo cuando quiero usar una aplicación en Windows creada en Ubuntu.

- **Virtualización de entornos de desarrollo**: Cuando creamos una aplicación o podemos comprobar un script, necisitamos comprobar si nuestro programa va a funcionar en varias distribuciones. Utilizamos esta virtualización para poder comprobar nuestro programa en varias distribuciones.

**Comment by Chentaco** [comment]
- **Virtualización plena:** Si quiero utilizar distintos sistemas operativos sin tener que realizar particiones o utilizar ordenadores distintos, recurriendo así al uso de máquinas virtuales como VirtualBox o WMWare.  

- **Virtualización parcial:** Cualquier escenario donde se tenga un recurso que se comparte en distintos clientes o usuarios, a los cuales se les "hace creer" que están accediendo al recurso completo.

- **Virtualización a nivel de sistema operativo:** La descripción dice que aisla a los sistemas anfritiones y clientes entre sí, pero usan el mismo SO. Las VPS es el ejemplo que se me ocurre. 

- **Virtualización de aplicaciones:** Se usa en el caso que necesite ejecutar una aplicación que requiera de un SO en concreto y no esté disponible para el SO que nosotros tenemos. Por ejemplo, si usamos Linux y necesitamos ejecutar una apliación .exe de Windows.

- **Virtualización de entornos de desarrollo:** En el caso de que tengamos el código de un proyecto y necesitemos una versión con intérpretes y librerias que no son compatibles con la versión actual que tenemos, utilizaremos esta virtualización.

**Comment by juanjetomas** [comment]
- **Virtualización plena**: La uso cuando quiero usar otro sistema operativo diferente a mío habitual sin tener que realizar particiones y sin ponerlo en peligro. En mi caso he usado hipervisor de tipo 2, ya que el software de virtualización se ejecuta sobre el sistema operativo anfitrión, 
- **Virtualización parcial**: Se usa cuando se quiere virtualizar solo parte del hardware del equipo. El sistema operativo no corre en en los componentes virtuales, pero algunas aplicaciones sí lo hacen.
- **Paravirtualización**: Se usa para obtener un rendimiento mayor que la virtualización completa ya que el hipervisor utilizado es más delgado y los invitados hablan directamente con el hardware del host. Para ello el S.O. debe estar modificado con tal propósito.
- **Virtualización a nivel de sistema operativo**: Se usa para aislar a unos usuarios de otros cuando están usando el sistema evitándose así las interferencias entre ellos y a su vez reduciendo las bajadas de rendimiento como ocurre en los servidores virtuales privados.
- **Virtualización de aplicaciones**: Se usa cuando queremos trabajar en un sistema operativo como anfitrión y usar cierta aplicación compatible con otro, pero no queremos instalarlo ni necesitamos toda su funcionalidad. Un ejemplo es Wine.
- **Virtualización de entornos de desarrollo**: Se usa cuando se quiere ejecutar sobre todo scripts con unas condiciones específicas que cumplía el entorno bajo el que fueron desarrollados (por ejemplo, librerías) como ocurre en CDE.

**Comment by Lynares** [comment]
**-Virtualización plena:**
Al tener que trabajar con sistemas operativos virtualizados al completo en algunas prácticas, usando VirtualBox o VMWare.
**-Virtualización de aplicaciones:**
También me he encontrado con aplicaciones que solo estaban disponibles para Windows, en su mayoría para XP o anteriores, que al usar Linux he tenido que usar este tipo de virtualización para poder usarlos, como la gran mayoría de compañeros uso Wine para este cometido.

**Comment by danilcd** [comment]
- **Virtualización plena** la usaría para configurar mi propia configuración de un sistema que necesitase escalar fácilmente en función de la demanda.
- **Virtualización parcial** por ejemplo para un servicio de almacenamiento, virtualizando la memoria podemos facilitar la escalabilidad del hardware y el control de errores.
- **Virtualización a nivel de sistema operativo** para compartir la capacidad de un sistema potente en distintos terminales ligeros.
- **Virtualización de aplicaciones** para ejecutar aplicaciones que en tu sistema operativo no es posible. Se me ocurre que la plataforma [Steam](http://store.steampowered.com/about/) hace uso de este tipo de virtualización.
- **Virtualización de entornos de desarrollo** para testear el funcionamiento de aplicaciones en distintos entornos de forma más sencilla y rápida.

**Comment by VierkaJ** [comment]
Para poder disponer de diferentes sistemas operativos usaría una virtualización plena que permite ejecutar cada sistema operativo en su máquina virtual correspondiente (por ejemplo, VirtualBox).

Si quisiera usar una aplicación en un sistema operativo diferente, usaría una virtualización de aplicaciones (por ejemplo, WINE ejecuta una aplicación de Windows en Linux).

Para los programas escritos en Python donde se requieren diferentes versiones de librerías, usaría una virtualización de entorno de desarollo.

**Comment by antoniovj1** [comment]
- Virtualización plena: Para usar múltiples sistemas operativos en mi ordenador, sin tener que crear particiones y quitar espacio a mi SO habitual.

- Virtualización parcial: Se puede usar para usar múltiples discos duros como uno solo de mayor tamaño (RAID)

- Paravirtualización: Cuando se quieren usar una maquina virtual pero se necesita un rendimiento muy alto.

- Virtualización a nivel de sistema operativo: Puede ser útil cuando se tiene un servidor muy potente y se quiere que múltiples usuarios hagan uso de el pero simulando que cada uno esta usando un ordenador distinto.

- Virtualización de aplicaciones: Se puede usar cuando necesitamos ejecutar una aplicación que esta diseñada para otro sistema operativo.

- Virtualización de entornos de desarrollo: Este tipo de virtualización se puede usar para desarrollar una aplicación y mantener las dependencias controladas y aisladas del sistema operativo. Por ejemplo con virtualenv se puede hacer una aplicaron en python manteniendo unas dependencias con versiones distintas a las usadas en el SO.

**Comment by rubenjo7** [comment]
**Virtualización plena** --> Cuando necesite trabajar con sistemas operativos (Usaré cualquier tipo de máquina virtual, como VirtualBox).
**Virtualización parcial** --> La usaremos cuando queramos virtualizar solo parte del hardware del que disponemos.
**Virtualización a nivel de sistema operativo** --> Cuando necesitemos compartir la carga de un servidor muy potente.
**Virtualización de aplicaciones** --> Cuando queremos ejecutar aplicaciones pero nuestro sistema operativo no nos lo permite.

**Comment by makelele29** [comment]
- Virtualización plena : Para usar diferentes sistemas operativos o maquinas recurriría a una virtualización completa o plena (VMware,VirtualBox,etc).
- Virtualización de aplicaciones: En el caso de querer usar un ejecutable .exe o aplicaciones de Windows ( u otro sistema operativo) en un sistema UNIX/Linux usaría una virtualización de aplicaciones como por ejemplo Wine.
- Virtualización en entornos de desarrollo: cuando queremos trabajar con una determinada versión sin modificar la versión que tenemos, un claro ejemplo es Python con la versión 2.7 y la 3.

**Comment by manuasir** [comment]
-  *Virtualización plena*: útil por ejemplo cuando lo que se pretende es economizar costes de hardware. Una sola máquina física puede ser útil para operar con distintos servidores al mismo tiempo sin perder recursos en ejecutar un sistema operativo 'host'.
- *Virtualización parcial* : Recomendable cuando se pretende proporcionar una capa de abstracción al hardware, como por ejemplo en el caso de un servidor con un sistema de almacenamiento en RAID. Se pueden añadir nodos (discos) de forma transparente.
- *Virtualización a nivel de sistema operativo*: Un caso de uso puede ser KVM en sistemas Linux, en el cual se crean **namespaces**  aislados para ejecutar una nueva instancia de sistema independiente al espacio de direcciones del usuario.
- *Virtualización de aplicaciones*: Caso de **wine** en Linux o **bash** en la nueva versión de Windows 10. Es posible ejecutar aplicaciones nativas de cada sistema.
- *Virtualización de entornos de desarrollo*: Un caso de uso podría ser NVM para NodeJS, desde el cual se automatiza la modificación de las distintas dependencias y variables de entorno para simular un escenario adaptado a las necesidades y versiones que se le requieran.

**Comment by cr13** [comment]
Para una virtualización plena o completa usaría máquinas virtuales ya que se pueden tener varios sistemas operativos completos y distintos, utilizando hipervisores como son VMware Player o VirtualBox, etc.

Si quisiéramos ejecutar aplicaciones de  Windows u otro sistema operativo en Linux, cómo por ejemplo, usando WINE usaría una virtualización de aplicación 

Si quisiéramos tener nuestro servicio de almacenamiento, virtualizando la memoria utilizaría virtualización parcial ya que nos facilita la escalabilidad del hardware y el control de errores

Usaría la virtualización de entornos de desarrollo en el caso de tener que usar dos versiones de phyton y evitar así crear conflictos con el sistema u otros proyectos.

**Comment by insua1990** [comment]
Virtualización plena para ejecutar máquinas virtuales con sistemas operativos diferentes.
Virtualización de entornos de desarrollo para ejecutar lenguajes evitando conflictos.
Virtualización de aplicaciones para empaquetar aplicaciones y que se ejecuten de forma independiente mediante emuladores.

**Comment by JiaqiWa** [comment]
**Virtualización plena** : para trabajar con distintas sistemas operativa usando un hipervisor como por ejemplo VirtualBox. 

**Virtualización de aplicaciones**: para poder ejecutar de un sistema operativo en otro sistemas, como ejecutando aplicaciones de window en linux usando WINE o por ejemple en el ejercicio 3 de este tema , hemos empaquetado el programa  usando CDE, de esta forma que este programa podrá ejecutar en distintas sistemas de Linux. 

**Virtualización de entorno de desarrollo**: cuando varios trabaja en el mismo proyecto es conveniente que todos tengan el mismo entorno de desarrollo para evitar posible conflicto, por ejemplo, trabajar en distintas versiones de Python.

**Comment by Miguelmoral** [comment]
-Virtualización plena : Es el tipo de virtualización en el cuál se utiliza un hipervisor tipo Vmwarepara utilizar un sistema operativo determinado.
- Virtualización de entorno de desarrollo: Por ejemplo la virtualización realizada con vagrant, se utiliza para evitar conflictos de versiones entre máquinas, de esta forma todo el mundo trabajará con el mismo entorno de trabajo.
-Virtualización de aplicaciones: Se utiliza para ejecutar programas los cuales no están disponibles en ese sistema operativo, un ejemplo podría ser wine para ejecutar aplicaciones de windows en Linux

**Comment by iCachurro** [comment]
**-Virtualización plena -->** Programa para virtualizar un sistema completo.
**-Virtualización parcial -->** Para simular más memoria RAM de la que dispongo, el SO virtualiza parte del disco duro como si fuera memoría RAM.
**-Virtualización a nivel de sistema operativo -->** En un servidor pueden convivir varios SO virtualizados, de esta forma, se virtualizan los recursos y ellos creen que son los anfitriones.
**-Virtualización de aplicaciones -->** Para poder usar una aplicación que ha sido creada para un SO distinto al anfitrión.
**-Virtualización de entornos de desarrollo -->** Para poder comprobar que lo desarrollado funciona, sin afectar ni perjudiar al anfitrión ante u posible error.

**Comment by JJ** [comment]
Amigo @Chentaco has vuelto a cerrar esto. Los closes y demás, en vuestros proyectos, por favor.

**Comment by Chentaco** [comment]
@JJ Ha sido un error por utilizar un commit que ya hice, lo siento.

**Comment by adalsa91** [comment]
Si necesito ejecutar varias aplicaciones y funcionalidades de un SO de forma simultanea utilizo virtualización plena mediante el uso de hipervisores, normalmente de tipo 2 como VirtualBox. En caso de necesitar ejecutar solo una apliación específica sin necesidad explícita de las demás funciones del SO usaría virtualización de aplicaciones usando algún emulador como Wine. Cuando se necesita probar aplicaciones en un entorno seguro y que simule al de producción es recomendable usar contenedores (virtualización a nivel de sistema operativo) como por ejemplo Docker.

**Comment by Mustapha90** [comment]
-Virtualización plena: La uso cuando necesito trabajar con varios sistemas operativos, usando algún hipervisor, por ejemplo (VirtualBox, VMWare)
-Virtualización de aplicaciones: La uso para ejecutar aplicaciones de windows en Linux usando el paquete WINE
-Virtualización a nivel de sistema operativo: Cuando es necesario tener múltiples servidores virtuales aislados y seguros en un solo servidor físico, ejemplos: Linux-VServer, Virtuozzo, OpenVZ, Solaris Containers y FreeBSD Jails.

**Comment by RosaOR** [comment]
-**Virtualización plena:** Es la opción que utilizo casi siempre, ya que te ofrece todas las funcionalidades de un SO completo. También para poder utilizar dos SO a la vez. Por ejemplo para esto se puede utilizar VirtualBox.

 -**Virtualización parcial:** Es utilizado para compartir recursos con varios usuarios.

 -**Virtualización de aplicaciones:** Se utiliza para ejecutar programas o aplicaciones que no estan disponibles en nuestro SO. Por ejemplo Wine para ejecutar programas de Windows en Linux.

 -**Virtualización de entornos de desarrollo:** Utilizamos esta virtualización, cuando hacemos un scrip y queremos comprobar que funciona en varias distribuciones.

**Comment by pctmoreno** [comment]
**-Virtualización plena:** Es la opción que siempre utilizo, ya que es muy cómoda de utilizar gracias a hipervisores o programas de control, llegando a virtualizar múltiples máquinas al mismo tiempo. Algunos de los que he usadon son VirtualBox y VMware.
**-Virtualización parcial:** Se puede utilizar para virtualizar como por ejemplo la memoria ram y repartirla según nuestras necesidades:
**-Virtualización de aplicaciones:** Se utiliza para virtualizar aplicaciones como por ejemplo, aplicaciones de windows en linux, para ello podemos utilizar WINE.
**-Virtualización a nivel de sistema operativo:** Se utiliza para virtualizar varios sistemas operativos en un mismo computador de manera independiente.
**-Virtualización de entornos de desarrollo:** Este tipo de virtualización es muy recomendable cuando estamos en un entorno de desarrollo con diferentes proyectos, los cuales pueden tener diferentes versiones de las dependencias así como librerías diferentes. En python se puede usar virtualenv el cual nos permite crear un entorno virtual y cambiar de entorno virtual con la orden "workon" seguido del nombre asignado al entorno de desarrollo virtual, una vez dentro, podemos instalar librerías y demás y solo estarán disponibles en ese entorno de desarrollo, sin afectar a los demás.

**Comment by MariaMma6** [comment]
- Virtualización plena: nos proporciona la ventaja de poseer varios SO en un mismo ordenador de forma aislada entre ellos, además de ello, nuestro SO anfitrión se encuentra seguro e independiente del resto de sistemas operativos. Ejemplo: VMWare o VirtualBox.
- Virtualización parcial: Utilizado con el fin de compartir recursos entre varios usuarios, haciendo creer a cada uno de ellos que poseen el recurso en su totalidad.
- Virtualización de aplicaciones: Útil para un caso en que queramos utilizar una aplicación de un sistema operativo (Windows por ejemplo), en otro sistema operativo (Linux por ejemplo) que no posee dicha aplicación.
- Virtualización de entornos de desarrollo: En caso de querer realizar comprobar el funcionamiento de aplicaciones en diferentes entornos.
