### ISSUE TITLE
Enlace roto a práctica del segundo hito

### ISSUE THREAD

**Issue by Sergiopopoulos** [JJ/IV16-17#136]
En el archivo 3-semana.md, cuando le doy al enlace a la Práctica: guión del segundo hito del proyecto, me sale como enlace roto, y creo que el enlace correcto sería: http://jj.github.io/IV/documentos/proyecto/2.CI en vez de http://jj.github.io/IV/documentos/practicas/2.CI.

**Comment by JJ** [comment]
Eso merece un bonito pull request :-)

**Comment by klyone** [comment]
Ya ha sido confirmado el PR!!
