### ISSUE TITLE
Comando de upstream erroneo

### ISSUE THREAD

**Issue by elsudano** [JJ/IV16-17#15]
En este enlace [README.md](https://github.com/JJ/IV16-17/blob/master/objetivos/README.md) el comando que se usa para poder "sincronizar" el repositorio original con el repositorio propio, esta mal puesto que usa un repositorio obsoleto
el comando correcto sería:
`git remote add upstream git@github.com:JJ/IV16-17.git`
Si lo desea puedo hacer directamente un pull request con el comando correcto

**Comment by JJ** [comment]
¡Adelante!

**Comment by elsudano** [comment]
Se me adelantó Marcos :smile:
