### ISSUE TITLE
Error en el siguiente enlace

### ISSUE THREAD

**Issue by Antkk10** [JJ/IV16-17#2]
Este enlace me da error: https://github.com/JJ/IV16-17/practicas/0

**Comment by JJ** [comment]
¿Dónde está el enlace?

**Comment by aravergar** [comment]
*En este fichero*

https://github.com/JJ/IV16-17/blob/master/objetivos/README.md

**Comment by JJ** [comment]
Se mueve a JJ/IV#24

**Comment by JJ** [comment]
Solucionado. Gracias @Antkk10 y @aravergar .
